[package]
name = "uon-eoms-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
actix-web-actors = "4.2.0"
actix = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.1.0", features = ["postgres", "uuid", "chrono", "r2d2"] }
dotenvy = "0.15"
uuid = { version = "1.4", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8.3"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
tokio = { version = "1", features = ["full"] }
